/**
 * Alfresco Blockchain Agent
 * This is an API containing functions for blockchain integration with Alfresco.
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export namespace ModelError {
  export type LevelEnum = 'INFO' | 'WARNING' | 'FATAL';
  export const LevelEnum = {
    INFO: 'INFO' as LevelEnum,
    WARNING: 'WARNING' as LevelEnum,
    FATAL: 'FATAL' as LevelEnum
  }
}
